services:
  nginx:
    build:
      context: ./nginx
    container_name: HabitAppBackend-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DOMAIN=${DOMAIN:-localhost}
      - EMAIL=${EMAIL}
      - PORT=${PORT}
    restart: unless-stopped
    networks: 
      - proxy

  app:
    build:
      context: ./app
      args:
        PORT: ${PORT}
    container_name: HabitAppBackend-app
    expose:
      - ${PORT}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - internal
      - proxy
  
  postgres:
    image: postgres:alpine
    container_name: HabitAppBackend-postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
  
  redis:
    image: redis:alpine
    container_name: HabitAppBackend-redis
    command: redis-server --port ${REDIS_PORT} --requirepass ${REDIS_SECRET}
    networks:
      - internal

volumes:
  pgdata:

networks:
  internal:
  proxy:
